package dao;

import java.sql.SQLException;
import java.util.List;

import com.ibatis.common.util.PaginatedList;

import model.CarBean;
import model.CarBeanExample;

public interface CarBeanDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table carlist
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    int countByExample(CarBeanExample example) throws SQLException;
    
    public List carBeanSql(String sql) throws SQLException;
    public String[] getProducerNames() throws SQLException;
	public String[] getCarNames() throws SQLException;
    public PaginatedList selectPaginnatedByExample(CarBeanExample example, int listSize) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table carlist
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    int deleteByExample(CarBeanExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table carlist
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    int deleteByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table carlist
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    void insert(CarBean record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table carlist
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    void insertSelective(CarBean record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table carlist
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    List selectByExample(CarBeanExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table carlist
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    CarBean selectByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table carlist
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    int updateByExampleSelective(CarBean record, CarBeanExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table carlist
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    int updateByExample(CarBean record, CarBeanExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table carlist
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    int updateByPrimaryKeySelective(CarBean record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table carlist
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    int updateByPrimaryKey(CarBean record) throws SQLException;

	public String[] getCarNames(String prodcerName) throws SQLException;
}