package dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import java.sql.SQLException;
import java.util.List;
import model.Car;
import model.CarExample;

public class CarDAOImpl implements CarDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table cars
     *
     * @ibatorgenerated Sun Jul 12 22:13:41 CST 2009
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cars
     *
     * @ibatorgenerated Sun Jul 12 22:13:41 CST 2009
     */
    public CarDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cars
     *
     * @ibatorgenerated Sun Jul 12 22:13:41 CST 2009
     */
    public int countByExample(CarExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("cars.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cars
     *
     * @ibatorgenerated Sun Jul 12 22:13:41 CST 2009
     */
    public int deleteByExample(CarExample example) throws SQLException {
        int rows = sqlMapClient.delete("cars.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cars
     *
     * @ibatorgenerated Sun Jul 12 22:13:41 CST 2009
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
        Car key = new Car();
        key.setId(id);
        int rows = sqlMapClient.delete("cars.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cars
     *
     * @ibatorgenerated Sun Jul 12 22:13:41 CST 2009
     */
    public void insert(Car record) throws SQLException {
        sqlMapClient.insert("cars.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cars
     *
     * @ibatorgenerated Sun Jul 12 22:13:41 CST 2009
     */
    public void insertSelective(Car record) throws SQLException {
        sqlMapClient.insert("cars.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cars
     *
     * @ibatorgenerated Sun Jul 12 22:13:41 CST 2009
     */
    public List selectByExample(CarExample example) throws SQLException {
        List list = sqlMapClient.queryForList("cars.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cars
     *
     * @ibatorgenerated Sun Jul 12 22:13:41 CST 2009
     */
    public Car selectByPrimaryKey(Integer id) throws SQLException {
        Car key = new Car();
        key.setId(id);
        Car record = (Car) sqlMapClient.queryForObject("cars.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cars
     *
     * @ibatorgenerated Sun Jul 12 22:13:41 CST 2009
     */
    public int updateByExampleSelective(Car record, CarExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("cars.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cars
     *
     * @ibatorgenerated Sun Jul 12 22:13:41 CST 2009
     */
    public int updateByExample(Car record, CarExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("cars.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cars
     *
     * @ibatorgenerated Sun Jul 12 22:13:41 CST 2009
     */
    public int updateByPrimaryKeySelective(Car record) throws SQLException {
        int rows = sqlMapClient.update("cars.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cars
     *
     * @ibatorgenerated Sun Jul 12 22:13:41 CST 2009
     */
    public int updateByPrimaryKey(Car record) throws SQLException {
        int rows = sqlMapClient.update("cars.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table cars
     *
     * @ibatorgenerated Sun Jul 12 22:13:41 CST 2009
     */
    private static class UpdateByExampleParms extends CarExample {
        private Object record;

        public UpdateByExampleParms(Object record, CarExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}