package dao;

import java.sql.SQLException;
import java.util.List;

import com.ibatis.common.util.PaginatedList;

import model.GasRcd;
import model.GasRcdExample;
@SuppressWarnings("deprecation")

public interface GasRcdDAO {
	

	PaginatedList getRcdForUserName(String name,  int listSize) throws SQLException;
	
	PaginatedList getRcdForUserID(Integer id,  int listSize) throws SQLException;
	
	public String deleteLastRcdsForUserID(Integer id)throws SQLException;
	
	
	public GasRcd getLastRcdForUserID(Integer id) throws SQLException;
	
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gasrcds
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    int countByExample(GasRcdExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gasrcds
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    int deleteByExample(GasRcdExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gasrcds
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    int deleteByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gasrcds
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    void insert(GasRcd record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gasrcds
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    void insertSelective(GasRcd record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gasrcds
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    List selectByExample(GasRcdExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gasrcds
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    GasRcd selectByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gasrcds
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    int updateByExampleSelective(GasRcd record, GasRcdExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gasrcds
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    int updateByExample(GasRcd record, GasRcdExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gasrcds
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    int updateByPrimaryKeySelective(GasRcd record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gasrcds
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    int updateByPrimaryKey(GasRcd record) throws SQLException;

}