package dao;

import java.sql.SQLException;
import java.util.List;
import model.Report;
import model.ReportExample;

public interface ReportDAO {
	
	public Report getLastReportForUserID(Integer uid) throws SQLException; 
	
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table statistics
     *
     * @ibatorgenerated Sun Jul 12 22:19:06 CST 2009
     */
    int countByExample(ReportExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table statistics
     *
     * @ibatorgenerated Sun Jul 12 22:19:06 CST 2009
     */
    int deleteByExample(ReportExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table statistics
     *
     * @ibatorgenerated Sun Jul 12 22:19:06 CST 2009
     */
    int deleteByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table statistics
     *
     * @ibatorgenerated Sun Jul 12 22:19:06 CST 2009
     */
    void insert(Report record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table statistics
     *
     * @ibatorgenerated Sun Jul 12 22:19:06 CST 2009
     */
    void insertSelective(Report record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table statistics
     *
     * @ibatorgenerated Sun Jul 12 22:19:06 CST 2009
     */
    List selectByExample(ReportExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table statistics
     *
     * @ibatorgenerated Sun Jul 12 22:19:06 CST 2009
     */
    Report selectByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table statistics
     *
     * @ibatorgenerated Sun Jul 12 22:19:06 CST 2009
     */
    int updateByExampleSelective(Report record, ReportExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table statistics
     *
     * @ibatorgenerated Sun Jul 12 22:19:06 CST 2009
     */
    int updateByExample(Report record, ReportExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table statistics
     *
     * @ibatorgenerated Sun Jul 12 22:19:06 CST 2009
     */
    int updateByPrimaryKeySelective(Report record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table statistics
     *
     * @ibatorgenerated Sun Jul 12 22:19:06 CST 2009
     */
    int updateByPrimaryKey(Report record) throws SQLException;

	void deleteLastReportForUserID(int id) throws SQLException;
}