package model;

import java.util.Date;

public class CarBean {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column carlist.id
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column carlist.Model
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    private String model;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column carlist.Name
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column carlist.producer
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    private String producer;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column carlist.Trans
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    private String trans;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column carlist.power
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    private Float power;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column carlist.GoodLPM
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    private Float goodLPM;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column carlist.badLPM
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    private Float badLPM;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column carlist.AVGLPM
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    private Float AVGLPM;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column carlist.Factor
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    private Float factor;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column carlist.RealLPM
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    private Float realLPM;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column carlist.TimeStamp
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    private Date timeStamp;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column carlist.priceLevel
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    private String priceLevel;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column carlist.year
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    private Integer year;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column carlist.hybird
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    private Boolean hybird;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column carlist.updaeTime
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    private Date updaeTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column carlist.ctg1
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    private String ctg1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column carlist.ctg2
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    private String ctg2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column carlist.ctg3
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    private String ctg3;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column carlist.id
     *
     * @return the value of carlist.id
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column carlist.id
     *
     * @param id the value for carlist.id
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column carlist.Model
     *
     * @return the value of carlist.Model
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column carlist.Model
     *
     * @param model the value for carlist.Model
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column carlist.Name
     *
     * @return the value of carlist.Name
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column carlist.Name
     *
     * @param name the value for carlist.Name
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column carlist.producer
     *
     * @return the value of carlist.producer
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    public String getProducer() {
        return producer;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column carlist.producer
     *
     * @param producer the value for carlist.producer
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    public void setProducer(String producer) {
        this.producer = producer == null ? null : producer.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column carlist.Trans
     *
     * @return the value of carlist.Trans
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    public String getTrans() {
        return trans;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column carlist.Trans
     *
     * @param trans the value for carlist.Trans
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    public void setTrans(String trans) {
        this.trans = trans == null ? null : trans.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column carlist.power
     *
     * @return the value of carlist.power
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    public Float getPower() {
        return power;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column carlist.power
     *
     * @param power the value for carlist.power
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    public void setPower(Float power) {
        this.power = power;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column carlist.GoodLPM
     *
     * @return the value of carlist.GoodLPM
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    public Float getGoodLPM() {
        return goodLPM;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column carlist.GoodLPM
     *
     * @param goodLPM the value for carlist.GoodLPM
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    public void setGoodLPM(Float goodLPM) {
        this.goodLPM = goodLPM;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column carlist.badLPM
     *
     * @return the value of carlist.badLPM
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    public Float getBadLPM() {
        return badLPM;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column carlist.badLPM
     *
     * @param badLPM the value for carlist.badLPM
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    public void setBadLPM(Float badLPM) {
        this.badLPM = badLPM;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column carlist.AVGLPM
     *
     * @return the value of carlist.AVGLPM
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    public Float getAVGLPM() {
        return AVGLPM;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column carlist.AVGLPM
     *
     * @param AVGLPM the value for carlist.AVGLPM
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    public void setAVGLPM(Float AVGLPM) {
        this.AVGLPM = AVGLPM;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column carlist.Factor
     *
     * @return the value of carlist.Factor
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    public Float getFactor() {
        return factor;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column carlist.Factor
     *
     * @param factor the value for carlist.Factor
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    public void setFactor(Float factor) {
        this.factor = factor;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column carlist.RealLPM
     *
     * @return the value of carlist.RealLPM
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    public Float getRealLPM() {
        return realLPM;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column carlist.RealLPM
     *
     * @param realLPM the value for carlist.RealLPM
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    public void setRealLPM(Float realLPM) {
        this.realLPM = realLPM;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column carlist.TimeStamp
     *
     * @return the value of carlist.TimeStamp
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    public Date getTimeStamp() {
        return timeStamp;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column carlist.TimeStamp
     *
     * @param timeStamp the value for carlist.TimeStamp
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column carlist.priceLevel
     *
     * @return the value of carlist.priceLevel
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    public String getPriceLevel() {
        return priceLevel;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column carlist.priceLevel
     *
     * @param priceLevel the value for carlist.priceLevel
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    public void setPriceLevel(String priceLevel) {
        this.priceLevel = priceLevel == null ? null : priceLevel.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column carlist.year
     *
     * @return the value of carlist.year
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column carlist.year
     *
     * @param year the value for carlist.year
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column carlist.hybird
     *
     * @return the value of carlist.hybird
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    public Boolean getHybird() {
        return hybird;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column carlist.hybird
     *
     * @param hybird the value for carlist.hybird
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    public void setHybird(Boolean hybird) {
        this.hybird = hybird;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column carlist.updaeTime
     *
     * @return the value of carlist.updaeTime
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    public Date getUpdaeTime() {
        return updaeTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column carlist.updaeTime
     *
     * @param updaeTime the value for carlist.updaeTime
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    public void setUpdaeTime(Date updaeTime) {
        this.updaeTime = updaeTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column carlist.ctg1
     *
     * @return the value of carlist.ctg1
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    public String getCtg1() {
        return ctg1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column carlist.ctg1
     *
     * @param ctg1 the value for carlist.ctg1
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    public void setCtg1(String ctg1) {
        this.ctg1 = ctg1 == null ? null : ctg1.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column carlist.ctg2
     *
     * @return the value of carlist.ctg2
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    public String getCtg2() {
        return ctg2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column carlist.ctg2
     *
     * @param ctg2 the value for carlist.ctg2
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    public void setCtg2(String ctg2) {
        this.ctg2 = ctg2 == null ? null : ctg2.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column carlist.ctg3
     *
     * @return the value of carlist.ctg3
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    public String getCtg3() {
        return ctg3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column carlist.ctg3
     *
     * @param ctg3 the value for carlist.ctg3
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    public void setCtg3(String ctg3) {
        this.ctg3 = ctg3 == null ? null : ctg3.trim();
    }
}