package model;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class CarBeanExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table carlist
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table carlist
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    protected List oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table carlist
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    public CarBeanExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table carlist
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    protected CarBeanExample(CarBeanExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table carlist
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table carlist
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table carlist
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table carlist
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table carlist
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table carlist
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table carlist
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table carlist
     *
     * @ibatorgenerated Wed Jul 14 20:32:59 CST 2010
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return this;
        }

        public Criteria andIdIn(List values) {
            addCriterion("id in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List values) {
            addCriterion("id not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return this;
        }

        public Criteria andModelIsNull() {
            addCriterion("Model is null");
            return this;
        }

        public Criteria andModelIsNotNull() {
            addCriterion("Model is not null");
            return this;
        }

        public Criteria andModelEqualTo(String value) {
            addCriterion("Model =", value, "model");
            return this;
        }

        public Criteria andModelNotEqualTo(String value) {
            addCriterion("Model <>", value, "model");
            return this;
        }

        public Criteria andModelGreaterThan(String value) {
            addCriterion("Model >", value, "model");
            return this;
        }

        public Criteria andModelGreaterThanOrEqualTo(String value) {
            addCriterion("Model >=", value, "model");
            return this;
        }

        public Criteria andModelLessThan(String value) {
            addCriterion("Model <", value, "model");
            return this;
        }

        public Criteria andModelLessThanOrEqualTo(String value) {
            addCriterion("Model <=", value, "model");
            return this;
        }

        public Criteria andModelLike(String value) {
            addCriterion("Model like", value, "model");
            return this;
        }

        public Criteria andModelNotLike(String value) {
            addCriterion("Model not like", value, "model");
            return this;
        }

        public Criteria andModelIn(List values) {
            addCriterion("Model in", values, "model");
            return this;
        }

        public Criteria andModelNotIn(List values) {
            addCriterion("Model not in", values, "model");
            return this;
        }

        public Criteria andModelBetween(String value1, String value2) {
            addCriterion("Model between", value1, value2, "model");
            return this;
        }

        public Criteria andModelNotBetween(String value1, String value2) {
            addCriterion("Model not between", value1, value2, "model");
            return this;
        }

        public Criteria andNameIsNull() {
            addCriterion("Name is null");
            return this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("Name is not null");
            return this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("Name =", value, "name");
            return this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("Name <>", value, "name");
            return this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("Name >", value, "name");
            return this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("Name >=", value, "name");
            return this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("Name <", value, "name");
            return this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("Name <=", value, "name");
            return this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("Name like", value, "name");
            return this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("Name not like", value, "name");
            return this;
        }

        public Criteria andNameIn(List values) {
            addCriterion("Name in", values, "name");
            return this;
        }

        public Criteria andNameNotIn(List values) {
            addCriterion("Name not in", values, "name");
            return this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("Name between", value1, value2, "name");
            return this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("Name not between", value1, value2, "name");
            return this;
        }

        public Criteria andProducerIsNull() {
            addCriterion("producer is null");
            return this;
        }

        public Criteria andProducerIsNotNull() {
            addCriterion("producer is not null");
            return this;
        }

        public Criteria andProducerEqualTo(String value) {
            addCriterion("producer =", value, "producer");
            return this;
        }

        public Criteria andProducerNotEqualTo(String value) {
            addCriterion("producer <>", value, "producer");
            return this;
        }

        public Criteria andProducerGreaterThan(String value) {
            addCriterion("producer >", value, "producer");
            return this;
        }

        public Criteria andProducerGreaterThanOrEqualTo(String value) {
            addCriterion("producer >=", value, "producer");
            return this;
        }

        public Criteria andProducerLessThan(String value) {
            addCriterion("producer <", value, "producer");
            return this;
        }

        public Criteria andProducerLessThanOrEqualTo(String value) {
            addCriterion("producer <=", value, "producer");
            return this;
        }

        public Criteria andProducerLike(String value) {
            addCriterion("producer like", value, "producer");
            return this;
        }

        public Criteria andProducerNotLike(String value) {
            addCriterion("producer not like", value, "producer");
            return this;
        }

        public Criteria andProducerIn(List values) {
            addCriterion("producer in", values, "producer");
            return this;
        }

        public Criteria andProducerNotIn(List values) {
            addCriterion("producer not in", values, "producer");
            return this;
        }

        public Criteria andProducerBetween(String value1, String value2) {
            addCriterion("producer between", value1, value2, "producer");
            return this;
        }

        public Criteria andProducerNotBetween(String value1, String value2) {
            addCriterion("producer not between", value1, value2, "producer");
            return this;
        }

        public Criteria andTransIsNull() {
            addCriterion("Trans is null");
            return this;
        }

        public Criteria andTransIsNotNull() {
            addCriterion("Trans is not null");
            return this;
        }

        public Criteria andTransEqualTo(String value) {
            addCriterion("Trans =", value, "trans");
            return this;
        }

        public Criteria andTransNotEqualTo(String value) {
            addCriterion("Trans <>", value, "trans");
            return this;
        }

        public Criteria andTransGreaterThan(String value) {
            addCriterion("Trans >", value, "trans");
            return this;
        }

        public Criteria andTransGreaterThanOrEqualTo(String value) {
            addCriterion("Trans >=", value, "trans");
            return this;
        }

        public Criteria andTransLessThan(String value) {
            addCriterion("Trans <", value, "trans");
            return this;
        }

        public Criteria andTransLessThanOrEqualTo(String value) {
            addCriterion("Trans <=", value, "trans");
            return this;
        }

        public Criteria andTransLike(String value) {
            addCriterion("Trans like", value, "trans");
            return this;
        }

        public Criteria andTransNotLike(String value) {
            addCriterion("Trans not like", value, "trans");
            return this;
        }

        public Criteria andTransIn(List values) {
            addCriterion("Trans in", values, "trans");
            return this;
        }

        public Criteria andTransNotIn(List values) {
            addCriterion("Trans not in", values, "trans");
            return this;
        }

        public Criteria andTransBetween(String value1, String value2) {
            addCriterion("Trans between", value1, value2, "trans");
            return this;
        }

        public Criteria andTransNotBetween(String value1, String value2) {
            addCriterion("Trans not between", value1, value2, "trans");
            return this;
        }

        public Criteria andPowerIsNull() {
            addCriterion("power is null");
            return this;
        }

        public Criteria andPowerIsNotNull() {
            addCriterion("power is not null");
            return this;
        }

        public Criteria andPowerEqualTo(Float value) {
            addCriterion("power =", value, "power");
            return this;
        }

        public Criteria andPowerNotEqualTo(Float value) {
            addCriterion("power <>", value, "power");
            return this;
        }

        public Criteria andPowerGreaterThan(Float value) {
            addCriterion("power >", value, "power");
            return this;
        }

        public Criteria andPowerGreaterThanOrEqualTo(Float value) {
            addCriterion("power >=", value, "power");
            return this;
        }

        public Criteria andPowerLessThan(Float value) {
            addCriterion("power <", value, "power");
            return this;
        }

        public Criteria andPowerLessThanOrEqualTo(Float value) {
            addCriterion("power <=", value, "power");
            return this;
        }

        public Criteria andPowerIn(List values) {
            addCriterion("power in", values, "power");
            return this;
        }

        public Criteria andPowerNotIn(List values) {
            addCriterion("power not in", values, "power");
            return this;
        }

        public Criteria andPowerBetween(Float value1, Float value2) {
            addCriterion("power between", value1, value2, "power");
            return this;
        }

        public Criteria andPowerNotBetween(Float value1, Float value2) {
            addCriterion("power not between", value1, value2, "power");
            return this;
        }

        public Criteria andGoodLPMIsNull() {
            addCriterion("GoodLPM is null");
            return this;
        }

        public Criteria andGoodLPMIsNotNull() {
            addCriterion("GoodLPM is not null");
            return this;
        }

        public Criteria andGoodLPMEqualTo(Float value) {
            addCriterion("GoodLPM =", value, "goodLPM");
            return this;
        }

        public Criteria andGoodLPMNotEqualTo(Float value) {
            addCriterion("GoodLPM <>", value, "goodLPM");
            return this;
        }

        public Criteria andGoodLPMGreaterThan(Float value) {
            addCriterion("GoodLPM >", value, "goodLPM");
            return this;
        }

        public Criteria andGoodLPMGreaterThanOrEqualTo(Float value) {
            addCriterion("GoodLPM >=", value, "goodLPM");
            return this;
        }

        public Criteria andGoodLPMLessThan(Float value) {
            addCriterion("GoodLPM <", value, "goodLPM");
            return this;
        }

        public Criteria andGoodLPMLessThanOrEqualTo(Float value) {
            addCriterion("GoodLPM <=", value, "goodLPM");
            return this;
        }

        public Criteria andGoodLPMIn(List values) {
            addCriterion("GoodLPM in", values, "goodLPM");
            return this;
        }

        public Criteria andGoodLPMNotIn(List values) {
            addCriterion("GoodLPM not in", values, "goodLPM");
            return this;
        }

        public Criteria andGoodLPMBetween(Float value1, Float value2) {
            addCriterion("GoodLPM between", value1, value2, "goodLPM");
            return this;
        }

        public Criteria andGoodLPMNotBetween(Float value1, Float value2) {
            addCriterion("GoodLPM not between", value1, value2, "goodLPM");
            return this;
        }

        public Criteria andBadLPMIsNull() {
            addCriterion("badLPM is null");
            return this;
        }

        public Criteria andBadLPMIsNotNull() {
            addCriterion("badLPM is not null");
            return this;
        }

        public Criteria andBadLPMEqualTo(Float value) {
            addCriterion("badLPM =", value, "badLPM");
            return this;
        }

        public Criteria andBadLPMNotEqualTo(Float value) {
            addCriterion("badLPM <>", value, "badLPM");
            return this;
        }

        public Criteria andBadLPMGreaterThan(Float value) {
            addCriterion("badLPM >", value, "badLPM");
            return this;
        }

        public Criteria andBadLPMGreaterThanOrEqualTo(Float value) {
            addCriterion("badLPM >=", value, "badLPM");
            return this;
        }

        public Criteria andBadLPMLessThan(Float value) {
            addCriterion("badLPM <", value, "badLPM");
            return this;
        }

        public Criteria andBadLPMLessThanOrEqualTo(Float value) {
            addCriterion("badLPM <=", value, "badLPM");
            return this;
        }

        public Criteria andBadLPMIn(List values) {
            addCriterion("badLPM in", values, "badLPM");
            return this;
        }

        public Criteria andBadLPMNotIn(List values) {
            addCriterion("badLPM not in", values, "badLPM");
            return this;
        }

        public Criteria andBadLPMBetween(Float value1, Float value2) {
            addCriterion("badLPM between", value1, value2, "badLPM");
            return this;
        }

        public Criteria andBadLPMNotBetween(Float value1, Float value2) {
            addCriterion("badLPM not between", value1, value2, "badLPM");
            return this;
        }

        public Criteria andAVGLPMIsNull() {
            addCriterion("AVGLPM is null");
            return this;
        }

        public Criteria andAVGLPMIsNotNull() {
            addCriterion("AVGLPM is not null");
            return this;
        }

        public Criteria andAVGLPMEqualTo(Float value) {
            addCriterion("AVGLPM =", value, "AVGLPM");
            return this;
        }

        public Criteria andAVGLPMNotEqualTo(Float value) {
            addCriterion("AVGLPM <>", value, "AVGLPM");
            return this;
        }

        public Criteria andAVGLPMGreaterThan(Float value) {
            addCriterion("AVGLPM >", value, "AVGLPM");
            return this;
        }

        public Criteria andAVGLPMGreaterThanOrEqualTo(Float value) {
            addCriterion("AVGLPM >=", value, "AVGLPM");
            return this;
        }

        public Criteria andAVGLPMLessThan(Float value) {
            addCriterion("AVGLPM <", value, "AVGLPM");
            return this;
        }

        public Criteria andAVGLPMLessThanOrEqualTo(Float value) {
            addCriterion("AVGLPM <=", value, "AVGLPM");
            return this;
        }

        public Criteria andAVGLPMIn(List values) {
            addCriterion("AVGLPM in", values, "AVGLPM");
            return this;
        }

        public Criteria andAVGLPMNotIn(List values) {
            addCriterion("AVGLPM not in", values, "AVGLPM");
            return this;
        }

        public Criteria andAVGLPMBetween(Float value1, Float value2) {
            addCriterion("AVGLPM between", value1, value2, "AVGLPM");
            return this;
        }

        public Criteria andAVGLPMNotBetween(Float value1, Float value2) {
            addCriterion("AVGLPM not between", value1, value2, "AVGLPM");
            return this;
        }

        public Criteria andFactorIsNull() {
            addCriterion("Factor is null");
            return this;
        }

        public Criteria andFactorIsNotNull() {
            addCriterion("Factor is not null");
            return this;
        }

        public Criteria andFactorEqualTo(Float value) {
            addCriterion("Factor =", value, "factor");
            return this;
        }

        public Criteria andFactorNotEqualTo(Float value) {
            addCriterion("Factor <>", value, "factor");
            return this;
        }

        public Criteria andFactorGreaterThan(Float value) {
            addCriterion("Factor >", value, "factor");
            return this;
        }

        public Criteria andFactorGreaterThanOrEqualTo(Float value) {
            addCriterion("Factor >=", value, "factor");
            return this;
        }

        public Criteria andFactorLessThan(Float value) {
            addCriterion("Factor <", value, "factor");
            return this;
        }

        public Criteria andFactorLessThanOrEqualTo(Float value) {
            addCriterion("Factor <=", value, "factor");
            return this;
        }

        public Criteria andFactorIn(List values) {
            addCriterion("Factor in", values, "factor");
            return this;
        }

        public Criteria andFactorNotIn(List values) {
            addCriterion("Factor not in", values, "factor");
            return this;
        }

        public Criteria andFactorBetween(Float value1, Float value2) {
            addCriterion("Factor between", value1, value2, "factor");
            return this;
        }

        public Criteria andFactorNotBetween(Float value1, Float value2) {
            addCriterion("Factor not between", value1, value2, "factor");
            return this;
        }

        public Criteria andRealLPMIsNull() {
            addCriterion("RealLPM is null");
            return this;
        }

        public Criteria andRealLPMIsNotNull() {
            addCriterion("RealLPM is not null");
            return this;
        }

        public Criteria andRealLPMEqualTo(Float value) {
            addCriterion("RealLPM =", value, "realLPM");
            return this;
        }

        public Criteria andRealLPMNotEqualTo(Float value) {
            addCriterion("RealLPM <>", value, "realLPM");
            return this;
        }

        public Criteria andRealLPMGreaterThan(Float value) {
            addCriterion("RealLPM >", value, "realLPM");
            return this;
        }

        public Criteria andRealLPMGreaterThanOrEqualTo(Float value) {
            addCriterion("RealLPM >=", value, "realLPM");
            return this;
        }

        public Criteria andRealLPMLessThan(Float value) {
            addCriterion("RealLPM <", value, "realLPM");
            return this;
        }

        public Criteria andRealLPMLessThanOrEqualTo(Float value) {
            addCriterion("RealLPM <=", value, "realLPM");
            return this;
        }

        public Criteria andRealLPMIn(List values) {
            addCriterion("RealLPM in", values, "realLPM");
            return this;
        }

        public Criteria andRealLPMNotIn(List values) {
            addCriterion("RealLPM not in", values, "realLPM");
            return this;
        }

        public Criteria andRealLPMBetween(Float value1, Float value2) {
            addCriterion("RealLPM between", value1, value2, "realLPM");
            return this;
        }

        public Criteria andRealLPMNotBetween(Float value1, Float value2) {
            addCriterion("RealLPM not between", value1, value2, "realLPM");
            return this;
        }

        public Criteria andTimeStampIsNull() {
            addCriterion("TimeStamp is null");
            return this;
        }

        public Criteria andTimeStampIsNotNull() {
            addCriterion("TimeStamp is not null");
            return this;
        }

        public Criteria andTimeStampEqualTo(Date value) {
            addCriterion("TimeStamp =", value, "timeStamp");
            return this;
        }

        public Criteria andTimeStampNotEqualTo(Date value) {
            addCriterion("TimeStamp <>", value, "timeStamp");
            return this;
        }

        public Criteria andTimeStampGreaterThan(Date value) {
            addCriterion("TimeStamp >", value, "timeStamp");
            return this;
        }

        public Criteria andTimeStampGreaterThanOrEqualTo(Date value) {
            addCriterion("TimeStamp >=", value, "timeStamp");
            return this;
        }

        public Criteria andTimeStampLessThan(Date value) {
            addCriterion("TimeStamp <", value, "timeStamp");
            return this;
        }

        public Criteria andTimeStampLessThanOrEqualTo(Date value) {
            addCriterion("TimeStamp <=", value, "timeStamp");
            return this;
        }

        public Criteria andTimeStampIn(List values) {
            addCriterion("TimeStamp in", values, "timeStamp");
            return this;
        }

        public Criteria andTimeStampNotIn(List values) {
            addCriterion("TimeStamp not in", values, "timeStamp");
            return this;
        }

        public Criteria andTimeStampBetween(Date value1, Date value2) {
            addCriterion("TimeStamp between", value1, value2, "timeStamp");
            return this;
        }

        public Criteria andTimeStampNotBetween(Date value1, Date value2) {
            addCriterion("TimeStamp not between", value1, value2, "timeStamp");
            return this;
        }

        public Criteria andPriceLevelIsNull() {
            addCriterion("priceLevel is null");
            return this;
        }

        public Criteria andPriceLevelIsNotNull() {
            addCriterion("priceLevel is not null");
            return this;
        }

        public Criteria andPriceLevelEqualTo(String value) {
            addCriterion("priceLevel =", value, "priceLevel");
            return this;
        }

        public Criteria andPriceLevelNotEqualTo(String value) {
            addCriterion("priceLevel <>", value, "priceLevel");
            return this;
        }

        public Criteria andPriceLevelGreaterThan(String value) {
            addCriterion("priceLevel >", value, "priceLevel");
            return this;
        }

        public Criteria andPriceLevelGreaterThanOrEqualTo(String value) {
            addCriterion("priceLevel >=", value, "priceLevel");
            return this;
        }

        public Criteria andPriceLevelLessThan(String value) {
            addCriterion("priceLevel <", value, "priceLevel");
            return this;
        }

        public Criteria andPriceLevelLessThanOrEqualTo(String value) {
            addCriterion("priceLevel <=", value, "priceLevel");
            return this;
        }

        public Criteria andPriceLevelLike(String value) {
            addCriterion("priceLevel like", value, "priceLevel");
            return this;
        }

        public Criteria andPriceLevelNotLike(String value) {
            addCriterion("priceLevel not like", value, "priceLevel");
            return this;
        }

        public Criteria andPriceLevelIn(List values) {
            addCriterion("priceLevel in", values, "priceLevel");
            return this;
        }

        public Criteria andPriceLevelNotIn(List values) {
            addCriterion("priceLevel not in", values, "priceLevel");
            return this;
        }

        public Criteria andPriceLevelBetween(String value1, String value2) {
            addCriterion("priceLevel between", value1, value2, "priceLevel");
            return this;
        }

        public Criteria andPriceLevelNotBetween(String value1, String value2) {
            addCriterion("priceLevel not between", value1, value2, "priceLevel");
            return this;
        }

        public Criteria andYearIsNull() {
            addCriterion("year is null");
            return this;
        }

        public Criteria andYearIsNotNull() {
            addCriterion("year is not null");
            return this;
        }

        public Criteria andYearEqualTo(Integer value) {
            addCriterion("year =", value, "year");
            return this;
        }

        public Criteria andYearNotEqualTo(Integer value) {
            addCriterion("year <>", value, "year");
            return this;
        }

        public Criteria andYearGreaterThan(Integer value) {
            addCriterion("year >", value, "year");
            return this;
        }

        public Criteria andYearGreaterThanOrEqualTo(Integer value) {
            addCriterion("year >=", value, "year");
            return this;
        }

        public Criteria andYearLessThan(Integer value) {
            addCriterion("year <", value, "year");
            return this;
        }

        public Criteria andYearLessThanOrEqualTo(Integer value) {
            addCriterion("year <=", value, "year");
            return this;
        }

        public Criteria andYearIn(List values) {
            addCriterion("year in", values, "year");
            return this;
        }

        public Criteria andYearNotIn(List values) {
            addCriterion("year not in", values, "year");
            return this;
        }

        public Criteria andYearBetween(Integer value1, Integer value2) {
            addCriterion("year between", value1, value2, "year");
            return this;
        }

        public Criteria andYearNotBetween(Integer value1, Integer value2) {
            addCriterion("year not between", value1, value2, "year");
            return this;
        }

        public Criteria andHybirdIsNull() {
            addCriterion("hybird is null");
            return this;
        }

        public Criteria andHybirdIsNotNull() {
            addCriterion("hybird is not null");
            return this;
        }

        public Criteria andHybirdEqualTo(Boolean value) {
            addCriterion("hybird =", value, "hybird");
            return this;
        }

        public Criteria andHybirdNotEqualTo(Boolean value) {
            addCriterion("hybird <>", value, "hybird");
            return this;
        }

        public Criteria andHybirdGreaterThan(Boolean value) {
            addCriterion("hybird >", value, "hybird");
            return this;
        }

        public Criteria andHybirdGreaterThanOrEqualTo(Boolean value) {
            addCriterion("hybird >=", value, "hybird");
            return this;
        }

        public Criteria andHybirdLessThan(Boolean value) {
            addCriterion("hybird <", value, "hybird");
            return this;
        }

        public Criteria andHybirdLessThanOrEqualTo(Boolean value) {
            addCriterion("hybird <=", value, "hybird");
            return this;
        }

        public Criteria andHybirdIn(List values) {
            addCriterion("hybird in", values, "hybird");
            return this;
        }

        public Criteria andHybirdNotIn(List values) {
            addCriterion("hybird not in", values, "hybird");
            return this;
        }

        public Criteria andHybirdBetween(Boolean value1, Boolean value2) {
            addCriterion("hybird between", value1, value2, "hybird");
            return this;
        }

        public Criteria andHybirdNotBetween(Boolean value1, Boolean value2) {
            addCriterion("hybird not between", value1, value2, "hybird");
            return this;
        }

        public Criteria andUpdaeTimeIsNull() {
            addCriterion("updaeTime is null");
            return this;
        }

        public Criteria andUpdaeTimeIsNotNull() {
            addCriterion("updaeTime is not null");
            return this;
        }

        public Criteria andUpdaeTimeEqualTo(Date value) {
            addCriterion("updaeTime =", value, "updaeTime");
            return this;
        }

        public Criteria andUpdaeTimeNotEqualTo(Date value) {
            addCriterion("updaeTime <>", value, "updaeTime");
            return this;
        }

        public Criteria andUpdaeTimeGreaterThan(Date value) {
            addCriterion("updaeTime >", value, "updaeTime");
            return this;
        }

        public Criteria andUpdaeTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("updaeTime >=", value, "updaeTime");
            return this;
        }

        public Criteria andUpdaeTimeLessThan(Date value) {
            addCriterion("updaeTime <", value, "updaeTime");
            return this;
        }

        public Criteria andUpdaeTimeLessThanOrEqualTo(Date value) {
            addCriterion("updaeTime <=", value, "updaeTime");
            return this;
        }

        public Criteria andUpdaeTimeIn(List values) {
            addCriterion("updaeTime in", values, "updaeTime");
            return this;
        }

        public Criteria andUpdaeTimeNotIn(List values) {
            addCriterion("updaeTime not in", values, "updaeTime");
            return this;
        }

        public Criteria andUpdaeTimeBetween(Date value1, Date value2) {
            addCriterion("updaeTime between", value1, value2, "updaeTime");
            return this;
        }

        public Criteria andUpdaeTimeNotBetween(Date value1, Date value2) {
            addCriterion("updaeTime not between", value1, value2, "updaeTime");
            return this;
        }

        public Criteria andCtg1IsNull() {
            addCriterion("ctg1 is null");
            return this;
        }

        public Criteria andCtg1IsNotNull() {
            addCriterion("ctg1 is not null");
            return this;
        }

        public Criteria andCtg1EqualTo(String value) {
            addCriterion("ctg1 =", value, "ctg1");
            return this;
        }

        public Criteria andCtg1NotEqualTo(String value) {
            addCriterion("ctg1 <>", value, "ctg1");
            return this;
        }

        public Criteria andCtg1GreaterThan(String value) {
            addCriterion("ctg1 >", value, "ctg1");
            return this;
        }

        public Criteria andCtg1GreaterThanOrEqualTo(String value) {
            addCriterion("ctg1 >=", value, "ctg1");
            return this;
        }

        public Criteria andCtg1LessThan(String value) {
            addCriterion("ctg1 <", value, "ctg1");
            return this;
        }

        public Criteria andCtg1LessThanOrEqualTo(String value) {
            addCriterion("ctg1 <=", value, "ctg1");
            return this;
        }

        public Criteria andCtg1Like(String value) {
            addCriterion("ctg1 like", value, "ctg1");
            return this;
        }

        public Criteria andCtg1NotLike(String value) {
            addCriterion("ctg1 not like", value, "ctg1");
            return this;
        }

        public Criteria andCtg1In(List values) {
            addCriterion("ctg1 in", values, "ctg1");
            return this;
        }

        public Criteria andCtg1NotIn(List values) {
            addCriterion("ctg1 not in", values, "ctg1");
            return this;
        }

        public Criteria andCtg1Between(String value1, String value2) {
            addCriterion("ctg1 between", value1, value2, "ctg1");
            return this;
        }

        public Criteria andCtg1NotBetween(String value1, String value2) {
            addCriterion("ctg1 not between", value1, value2, "ctg1");
            return this;
        }

        public Criteria andCtg2IsNull() {
            addCriterion("ctg2 is null");
            return this;
        }

        public Criteria andCtg2IsNotNull() {
            addCriterion("ctg2 is not null");
            return this;
        }

        public Criteria andCtg2EqualTo(String value) {
            addCriterion("ctg2 =", value, "ctg2");
            return this;
        }

        public Criteria andCtg2NotEqualTo(String value) {
            addCriterion("ctg2 <>", value, "ctg2");
            return this;
        }

        public Criteria andCtg2GreaterThan(String value) {
            addCriterion("ctg2 >", value, "ctg2");
            return this;
        }

        public Criteria andCtg2GreaterThanOrEqualTo(String value) {
            addCriterion("ctg2 >=", value, "ctg2");
            return this;
        }

        public Criteria andCtg2LessThan(String value) {
            addCriterion("ctg2 <", value, "ctg2");
            return this;
        }

        public Criteria andCtg2LessThanOrEqualTo(String value) {
            addCriterion("ctg2 <=", value, "ctg2");
            return this;
        }

        public Criteria andCtg2Like(String value) {
            addCriterion("ctg2 like", value, "ctg2");
            return this;
        }

        public Criteria andCtg2NotLike(String value) {
            addCriterion("ctg2 not like", value, "ctg2");
            return this;
        }

        public Criteria andCtg2In(List values) {
            addCriterion("ctg2 in", values, "ctg2");
            return this;
        }

        public Criteria andCtg2NotIn(List values) {
            addCriterion("ctg2 not in", values, "ctg2");
            return this;
        }

        public Criteria andCtg2Between(String value1, String value2) {
            addCriterion("ctg2 between", value1, value2, "ctg2");
            return this;
        }

        public Criteria andCtg2NotBetween(String value1, String value2) {
            addCriterion("ctg2 not between", value1, value2, "ctg2");
            return this;
        }

        public Criteria andCtg3IsNull() {
            addCriterion("ctg3 is null");
            return this;
        }

        public Criteria andCtg3IsNotNull() {
            addCriterion("ctg3 is not null");
            return this;
        }

        public Criteria andCtg3EqualTo(String value) {
            addCriterion("ctg3 =", value, "ctg3");
            return this;
        }

        public Criteria andCtg3NotEqualTo(String value) {
            addCriterion("ctg3 <>", value, "ctg3");
            return this;
        }

        public Criteria andCtg3GreaterThan(String value) {
            addCriterion("ctg3 >", value, "ctg3");
            return this;
        }

        public Criteria andCtg3GreaterThanOrEqualTo(String value) {
            addCriterion("ctg3 >=", value, "ctg3");
            return this;
        }

        public Criteria andCtg3LessThan(String value) {
            addCriterion("ctg3 <", value, "ctg3");
            return this;
        }

        public Criteria andCtg3LessThanOrEqualTo(String value) {
            addCriterion("ctg3 <=", value, "ctg3");
            return this;
        }

        public Criteria andCtg3Like(String value) {
            addCriterion("ctg3 like", value, "ctg3");
            return this;
        }

        public Criteria andCtg3NotLike(String value) {
            addCriterion("ctg3 not like", value, "ctg3");
            return this;
        }

        public Criteria andCtg3In(List values) {
            addCriterion("ctg3 in", values, "ctg3");
            return this;
        }

        public Criteria andCtg3NotIn(List values) {
            addCriterion("ctg3 not in", values, "ctg3");
            return this;
        }

        public Criteria andCtg3Between(String value1, String value2) {
            addCriterion("ctg3 between", value1, value2, "ctg3");
            return this;
        }

        public Criteria andCtg3NotBetween(String value1, String value2) {
            addCriterion("ctg3 not between", value1, value2, "ctg3");
            return this;
        }
    }
}