package model;

import java.util.Date;

public class GasRcd {

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gasrcds.id
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gasrcds.userId
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    private Integer userId;
    
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gasrcds.lastFueledTime
     *
     * @ibatorgenerated Sun Jul 19 10:32:13 CST 2009
     */
    private Date lastFueledTime = new Date(2999,12,1);


    public Date getLastFueledTime()
	{
		return lastFueledTime;
	}

	public void setLastFueledTime(Date lastFueledTime)
	{
		this.lastFueledTime = lastFueledTime;
	}

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gasrcds.fueledTime
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    private Date fueledTime = new Date();

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gasrcds.timeStamp
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    private Date timeStamp;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gasrcds.totalDistance
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    private Integer totalDistance = 0;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gasrcds.lastDistance
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    private Short lastDistance = 0;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gasrcds.fueledVolum
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    private Float fueledVolum =Float.valueOf("0");

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gasrcds.money
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    private Float money =Float.valueOf("0");

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gasrcds.isFull
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    private Boolean isFull;
    
    
    /**
     * !!!DON'T CHANGE THE DEFAULT VALUE "0" ! IT IS USED IN THE DATABASE QUERY!!!<BR>
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gasrcds.LPM
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    private Float LPM =Float.valueOf("0");

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gasrcds.place
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    private String place;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gasrcds.roadType
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    private String roadType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gasrcds.gasType
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    private String gasType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gasrcds.comment
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    private String comment;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gasrcds.id
     *
     * @return the value of gasrcds.id
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gasrcds.id
     *
     * @param id the value for gasrcds.id
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gasrcds.userId
     *
     * @return the value of gasrcds.userId
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gasrcds.userId
     *
     * @param userId the value for gasrcds.userId
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gasrcds.fueledTime
     *
     * @return the value of gasrcds.fueledTime
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    public Date getFueledTime() {
        return fueledTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gasrcds.fueledTime
     *
     * @param fueledTime the value for gasrcds.fueledTime
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    public void setFueledTime(Date fueledTime) {
        this.fueledTime = fueledTime;
    }
    
    /**
     * turn around for form data support by BeanUtil.populateBean()
     * @param fueledTime
     */
    public void setFueledTimeString(String fueledTime) {
    	
    	java.sql.Date date = java.sql.Date.valueOf(fueledTime);
        this.fueledTime = new Date(date.getTime());
    }
    
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gasrcds.timeStamp
     *
     * @return the value of gasrcds.timeStamp
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    public Date getTimeStamp() {
        return timeStamp;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gasrcds.timeStamp
     *
     * @param timeStamp the value for gasrcds.timeStamp
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gasrcds.totalDistance
     *
     * @return the value of gasrcds.totalDistance
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    public Integer getTotalDistance() {
        return totalDistance;
    }

    /**
     * The figure read form car meter.
     * 
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gasrcds.totalDistance
     *
     * @param totalDistance the value for gasrcds.totalDistance
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    public void setTotalDistance(Integer totalDistance) {
        this.totalDistance = totalDistance;
    }

    /**
     * LastDistance = the distance from last oil adding.
     * 
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gasrcds.lastDistance
     *
     * @return the value of gasrcds.lastDistance
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    public Short getLastDistance() {
        return lastDistance;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gasrcds.lastDistance
     *
     * @param lastDistance the value for gasrcds.lastDistance
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    public void setLastDistance(Short lastDistance) {
        this.lastDistance = lastDistance;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gasrcds.fueledVolum
     *
     * @return the value of gasrcds.fueledVolum
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    public Float getFueledVolum() {
        return fueledVolum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gasrcds.fueledVolum
     *
     * @param fueledVolum the value for gasrcds.fueledVolum
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    public void setFueledVolum(Float fueledVolum) {
        this.fueledVolum = fueledVolum;
    }

    /**
     * means price per liter.<br>
     * 
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gasrcds.money
     *
     * @return the value of gasrcds.money
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    public Float getMoney() {
        return money;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gasrcds.money
     *
     * @param money the value for gasrcds.money
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    public void setMoney(Float money) {
        this.money = money;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gasrcds.isFull
     *
     * @return the value of gasrcds.isFull
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    public Boolean getIsFull() {
        return isFull;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gasrcds.isFull
     *
     * @param isFull the value for gasrcds.isFull
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    public void setIsFull(Boolean isFull) {
        this.isFull = isFull;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gasrcds.LPM
     *
     * @return the value of gasrcds.LPM
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    public Float getLPM() {
        return LPM;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gasrcds.LPM
     *
     * @param LPM the value for gasrcds.LPM
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    public void setLPM(Float LPM) {
        this.LPM = LPM;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gasrcds.place
     *
     * @return the value of gasrcds.place
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    public String getPlace() {
        return place;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gasrcds.place
     *
     * @param place the value for gasrcds.place
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    public void setPlace(String place) {
        this.place = place == null ? null : place.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gasrcds.roadType
     *
     * @return the value of gasrcds.roadType
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    public String getRoadType() {
        return roadType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gasrcds.roadType
     *
     * @param roadType the value for gasrcds.roadType
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    public void setRoadType(String roadType) {
        this.roadType = roadType == null ? null : roadType.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gasrcds.gasType
     *
     * @return the value of gasrcds.gasType
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    public String getGasType() {
        return gasType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gasrcds.gasType
     *
     * @param gasType the value for gasrcds.gasType
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    public void setGasType(String gasType) {
        this.gasType = gasType == null ? null : gasType.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gasrcds.comment
     *
     * @return the value of gasrcds.comment
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gasrcds.comment
     *
     * @param comment the value for gasrcds.comment
     *
     * @ibatorgenerated Sun Jul 12 00:32:40 CST 2009
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}