package model;

import java.util.Date;

public class GasRcdKey {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column carlist.TimeStamp
     *
     * @ibatorgenerated Tue Jul 13 22:20:56 CST 2010
     */
    private Date timeStamp;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column carlist.id
     *
     * @ibatorgenerated Tue Jul 13 22:20:56 CST 2010
     */
    private Integer id;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column carlist.TimeStamp
     *
     * @return the value of carlist.TimeStamp
     *
     * @ibatorgenerated Tue Jul 13 22:20:56 CST 2010
     */
    public Date getTimeStamp() {
        return timeStamp;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column carlist.TimeStamp
     *
     * @param timeStamp the value for carlist.TimeStamp
     *
     * @ibatorgenerated Tue Jul 13 22:20:56 CST 2010
     */
    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column carlist.id
     *
     * @return the value of carlist.id
     *
     * @ibatorgenerated Tue Jul 13 22:20:56 CST 2010
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column carlist.id
     *
     * @param id the value for carlist.id
     *
     * @ibatorgenerated Tue Jul 13 22:20:56 CST 2010
     */
    public void setId(Integer id) {
        this.id = id;
    }
}