package model;

import java.util.Date;

public class GasRcdBak {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gasrcds.id
     *
     * @ibatorgenerated Sun Jun 07 20:18:00 CST 2009
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gasrcds.userId
     *
     * @ibatorgenerated Sun Jun 07 20:18:00 CST 2009
     */
    private Integer userId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gasrcds.fueledTime
     *
     * @ibatorgenerated Sun Jun 07 20:18:00 CST 2009
     */
    private Date fueledTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gasrcds.timeStamp
     *
     * @ibatorgenerated Sun Jun 07 20:18:00 CST 2009
     */
    private Date timeStamp;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gasrcds.totalDistance
     *
     * @ibatorgenerated Sun Jun 07 20:18:00 CST 2009
     */
    private Integer totalDistance;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gasrcds.lastDistance
     *
     * @ibatorgenerated Sun Jun 07 20:18:00 CST 2009
     */
    private Short lastDistance;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gasrcds.fueledVolum
     *
     * @ibatorgenerated Sun Jun 07 20:18:00 CST 2009
     */
    private Float fueledVolum;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gasrcds.gasType
     *
     * @ibatorgenerated Sun Jun 07 20:18:00 CST 2009
     */
    private String gasType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gasrcds.money
     *
     * @ibatorgenerated Sun Jun 07 20:18:00 CST 2009
     */
    private Float money;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gasrcds.isFull
     *
     * @ibatorgenerated Sun Jun 07 20:18:00 CST 2009
     */
    private Boolean isFull;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gasrcds.LPM
     *
     * @ibatorgenerated Sun Jun 07 20:18:00 CST 2009
     */
    private Float LPM;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gasrcds.place
     *
     * @ibatorgenerated Sun Jun 07 20:18:00 CST 2009
     */
    private String place;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gasrcds.roadType
     *
     * @ibatorgenerated Sun Jun 07 20:18:00 CST 2009
     */
    private String roadType;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gasrcds.id
     *
     * @return the value of gasrcds.id
     *
     * @ibatorgenerated Sun Jun 07 20:18:00 CST 2009
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gasrcds.id
     *
     * @param id the value for gasrcds.id
     *
     * @ibatorgenerated Sun Jun 07 20:18:00 CST 2009
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gasrcds.userId
     *
     * @return the value of gasrcds.userId
     *
     * @ibatorgenerated Sun Jun 07 20:18:00 CST 2009
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gasrcds.userId
     *
     * @param userId the value for gasrcds.userId
     *
     * @ibatorgenerated Sun Jun 07 20:18:00 CST 2009
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gasrcds.fueledTime
     *
     * @return the value of gasrcds.fueledTime
     *
     * @ibatorgenerated Sun Jun 07 20:18:00 CST 2009
     */
    public Date getFueledTime() {
        return fueledTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gasrcds.fueledTime
     *
     * @param fueledTime the value for gasrcds.fueledTime
     *
     * @ibatorgenerated Sun Jun 07 20:18:00 CST 2009
     */
    public void setFueledTime(Date fueledTime) {
        this.fueledTime = fueledTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gasrcds.timeStamp
     *
     * @return the value of gasrcds.timeStamp
     *
     * @ibatorgenerated Sun Jun 07 20:18:00 CST 2009
     */
    public Date getTimeStamp() {
        return timeStamp;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gasrcds.timeStamp
     *
     * @param timeStamp the value for gasrcds.timeStamp
     *
     * @ibatorgenerated Sun Jun 07 20:18:00 CST 2009
     */
    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gasrcds.totalDistance
     *
     * @return the value of gasrcds.totalDistance
     *
     * @ibatorgenerated Sun Jun 07 20:18:00 CST 2009
     */
    public Integer getTotalDistance() {
        return totalDistance;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gasrcds.totalDistance
     *
     * @param totalDistance the value for gasrcds.totalDistance
     *
     * @ibatorgenerated Sun Jun 07 20:18:00 CST 2009
     */
    public void setTotalDistance(Integer totalDistance) {
        this.totalDistance = totalDistance;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gasrcds.lastDistance
     *
     * @return the value of gasrcds.lastDistance
     *
     * @ibatorgenerated Sun Jun 07 20:18:00 CST 2009
     */
    public Short getLastDistance() {
        return lastDistance;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gasrcds.lastDistance
     *
     * @param lastDistance the value for gasrcds.lastDistance
     *
     * @ibatorgenerated Sun Jun 07 20:18:00 CST 2009
     */
    public void setLastDistance(Short lastDistance) {
        this.lastDistance = lastDistance;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gasrcds.fueledVolum
     *
     * @return the value of gasrcds.fueledVolum
     *
     * @ibatorgenerated Sun Jun 07 20:18:00 CST 2009
     */
    public Float getFueledVolum() {
        return fueledVolum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gasrcds.fueledVolum
     *
     * @param fueledVolum the value for gasrcds.fueledVolum
     *
     * @ibatorgenerated Sun Jun 07 20:18:00 CST 2009
     */
    public void setFueledVolum(Float fueledVolum) {
        this.fueledVolum = fueledVolum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gasrcds.gasType
     *
     * @return the value of gasrcds.gasType
     *
     * @ibatorgenerated Sun Jun 07 20:18:00 CST 2009
     */
    public Object getGasType() {
        return gasType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gasrcds.gasType
     *
     * @param gasType the value for gasrcds.gasType
     *
     * @ibatorgenerated Sun Jun 07 20:18:00 CST 2009
     */
    public void setGasType(String gasType) {
        this.gasType = gasType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gasrcds.money
     *
     * @return the value of gasrcds.money
     *
     * @ibatorgenerated Sun Jun 07 20:18:00 CST 2009
     */
    public Float getMoney() {
        return money;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gasrcds.money
     *
     * @param money the value for gasrcds.money
     *
     * @ibatorgenerated Sun Jun 07 20:18:00 CST 2009
     */
    public void setMoney(Float money) {
        this.money = money;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gasrcds.isFull
     *
     * @return the value of gasrcds.isFull
     *
     * @ibatorgenerated Sun Jun 07 20:18:00 CST 2009
     */
    public Boolean getIsFull() {
        return isFull;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gasrcds.isFull
     *
     * @param isFull the value for gasrcds.isFull
     *
     * @ibatorgenerated Sun Jun 07 20:18:00 CST 2009
     */
    public void setIsFull(Boolean isFull) {
        this.isFull = isFull;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gasrcds.LPM
     *
     * @return the value of gasrcds.LPM
     *
     * @ibatorgenerated Sun Jun 07 20:18:00 CST 2009
     */
    public Float getLPM() {
        return LPM;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gasrcds.LPM
     *
     * @param LPM the value for gasrcds.LPM
     *
     * @ibatorgenerated Sun Jun 07 20:18:00 CST 2009
     */
    public void setLPM(Float LPM) {
        this.LPM = LPM;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gasrcds.place
     *
     * @return the value of gasrcds.place
     *
     * @ibatorgenerated Sun Jun 07 20:18:00 CST 2009
     */
    public String getPlace() {
        return place;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gasrcds.place
     *
     * @param place the value for gasrcds.place
     *
     * @ibatorgenerated Sun Jun 07 20:18:00 CST 2009
     */
    public void setPlace(String place) {
        this.place = place == null ? null : place.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gasrcds.roadType
     *
     * @return the value of gasrcds.roadType
     *
     * @ibatorgenerated Sun Jun 07 20:18:00 CST 2009
     */
    public String getRoadType() {
        return roadType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gasrcds.roadType
     *
     * @param roadType the value for gasrcds.roadType
     *
     * @ibatorgenerated Sun Jun 07 20:18:00 CST 2009
     */
    public void setRoadType(String roadType) {
        this.roadType = roadType == null ? null : roadType.trim();
    }
}