package model;

import java.util.Date;

import com.sun.org.apache.bcel.internal.generic.NEW;

public class Report {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column statistics.id
     *
     * @ibatorgenerated Sun Jul 12 22:19:06 CST 2009
     */
    private Integer id;
    
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column statistics.fueledTime
     *
     * @ibatorgenerated Sun Jul 19 10:24:15 CST 2009
     */
    private Date fueledTime;


    public Date getFueledTime()
	{
		return fueledTime;
	}

	public void setFueledTime(Date fueledTime)
	{
		this.fueledTime = fueledTime;
	}

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column statistics.totalDistance
     *
     * @ibatorgenerated Sun Jul 12 22:19:06 CST 2009
     */
    private Integer totalDistance = Integer.valueOf(0);

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column statistics.totalGas
     *
     * @ibatorgenerated Sun Jul 12 22:19:06 CST 2009
     */
    private Float totalGas = Float.valueOf(0);

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column statistics.totalFee
     *
     * @ibatorgenerated Sun Jul 12 22:19:06 CST 2009
     */
    private Float totalFee = Float.valueOf(0);

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column statistics.recordedday
     *
     * @ibatorgenerated Sun Jul 12 22:19:06 CST 2009
     */
    private Short recordedday = Short.valueOf("0");

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column statistics.avgGasPrice
     *
     * @ibatorgenerated Sun Jul 12 22:19:06 CST 2009
     */
    private Float avgGasPrice = Float.valueOf(0);

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column statistics.milesPerDay
     *
     * @ibatorgenerated Sun Jul 12 22:19:06 CST 2009
     */
    private Integer milesPerDay = Integer.valueOf(0);;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column statistics.avgLPM
     *
     * @ibatorgenerated Sun Jul 12 22:19:06 CST 2009
     */
    private Float avgLPM = Float.valueOf(0);

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column statistics.avgFee
     *
     * @ibatorgenerated Sun Jul 12 22:19:06 CST 2009
     */
    private Float avgFee = Float.valueOf(0);

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column statistics.userId
     *
     * @ibatorgenerated Sun Jul 12 22:19:06 CST 2009
     */
    private Integer userId = Integer.valueOf(0);;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column statistics.timestamp
     *
     * @ibatorgenerated Sun Jul 12 22:19:06 CST 2009
     */
    private Date timestamp;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column statistics.id
     *
     * @return the value of statistics.id
     *
     * @ibatorgenerated Sun Jul 12 22:19:06 CST 2009
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column statistics.id
     *
     * @param id the value for statistics.id
     *
     * @ibatorgenerated Sun Jul 12 22:19:06 CST 2009
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column statistics.totalDistance
     *
     * @return the value of statistics.totalDistance
     *
     * @ibatorgenerated Sun Jul 12 22:19:06 CST 2009
     */
    public Integer getTotalDistance() {
        return totalDistance;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column statistics.totalDistance
     *
     * @param totalDistance the value for statistics.totalDistance
     *
     * @ibatorgenerated Sun Jul 12 22:19:06 CST 2009
     */
    public void setTotalDistance(Integer totalDistance) {
        this.totalDistance = totalDistance;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column statistics.totalGas
     *
     * @return the value of statistics.totalGas
     *
     * @ibatorgenerated Sun Jul 12 22:19:06 CST 2009
     */
    public Float getTotalGas() {
        return totalGas;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column statistics.totalGas
     *
     * @param totalGas the value for statistics.totalGas
     *
     * @ibatorgenerated Sun Jul 12 22:19:06 CST 2009
     */
    public void setTotalGas(Float totalGas) {
        this.totalGas = totalGas;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column statistics.totalFee
     *
     * @return the value of statistics.totalFee
     *
     * @ibatorgenerated Sun Jul 12 22:19:06 CST 2009
     */
    public Float getTotalFee() {
        return totalFee;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column statistics.totalFee
     *
     * @param totalFee the value for statistics.totalFee
     *
     * @ibatorgenerated Sun Jul 12 22:19:06 CST 2009
     */
    public void setTotalFee(Float totalFee) {
        this.totalFee = totalFee;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column statistics.recordedday
     *
     * @return the value of statistics.recordedday
     *
     * @ibatorgenerated Sun Jul 12 22:19:06 CST 2009
     */
    public Short getRecordedday() {
        return recordedday;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column statistics.recordedday
     *
     * @param recordedday the value for statistics.recordedday
     *
     * @ibatorgenerated Sun Jul 12 22:19:06 CST 2009
     */
    public void setRecordedday(Short recordedday) {
        this.recordedday = recordedday;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column statistics.avgGasPrice
     *
     * @return the value of statistics.avgGasPrice
     *
     * @ibatorgenerated Sun Jul 12 22:19:06 CST 2009
     */
    public Float getAvgGasPrice() {
        return avgGasPrice;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column statistics.avgGasPrice
     *
     * @param avgGasPrice the value for statistics.avgGasPrice
     *
     * @ibatorgenerated Sun Jul 12 22:19:06 CST 2009
     */
    public void setAvgGasPrice(Float avgGasPrice) {
        this.avgGasPrice = avgGasPrice;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column statistics.milesPerDay
     *
     * @return the value of statistics.milesPerDay
     *
     * @ibatorgenerated Sun Jul 12 22:19:06 CST 2009
     */
    public Integer getMilesPerDay() {
        return milesPerDay;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column statistics.milesPerDay
     *
     * @param milesPerDay the value for statistics.milesPerDay
     *
     * @ibatorgenerated Sun Jul 12 22:19:06 CST 2009
     */
    public void setMilesPerDay(Integer milesPerDay) {
        this.milesPerDay = milesPerDay;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column statistics.avgLPM
     *
     * @return the value of statistics.avgLPM
     *
     * @ibatorgenerated Sun Jul 12 22:19:06 CST 2009
     */
    public Float getAvgLPM() {
        return avgLPM;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column statistics.avgLPM
     *
     * @param avgLPM the value for statistics.avgLPM
     *
     * @ibatorgenerated Sun Jul 12 22:19:06 CST 2009
     */
    public void setAvgLPM(Float avgLPM) {
        this.avgLPM = avgLPM;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column statistics.avgFee
     *
     * @return the value of statistics.avgFee
     *
     * @ibatorgenerated Sun Jul 12 22:19:06 CST 2009
     */
    public Float getAvgFee() {
        return avgFee;
    }

    /**
     * avgFee(Jiao) = totalFee * 10/ totalDistance 
     * <br>
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column statistics.avgFee
     *
     * @param avgFee the value for statistics.avgFee
     *
     * @ibatorgenerated Sun Jul 12 22:19:06 CST 2009
     */
    public void setAvgFee(Float avgFee) {
        this.avgFee = avgFee;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column statistics.userId
     *
     * @return the value of statistics.userId
     *
     * @ibatorgenerated Sun Jul 12 22:19:06 CST 2009
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column statistics.userId
     *
     * @param userId the value for statistics.userId
     *
     * @ibatorgenerated Sun Jul 12 22:19:06 CST 2009
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column statistics.timestamp
     *
     * @return the value of statistics.timestamp
     *
     * @ibatorgenerated Sun Jul 12 22:19:06 CST 2009
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column statistics.timestamp
     *
     * @param timestamp the value for statistics.timestamp
     *
     * @ibatorgenerated Sun Jul 12 22:19:06 CST 2009
     */
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
}